[package]
name = "gc-immutable-collections"
version = "0.1.0"
authors = ["Aljoscha Meyer <mail@aljoscha-meyer.de>"]
edition = "2018"

[dependencies]
gc = "0.3.3"
gc_derive = "0.3.2"

[dev-dependencies]
proptest = "1.0.0"
proptest-derive = "0.2.0"
im = "15.0.0"
